/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcomponent;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.util.Random;

/**
 *
 * @author m78159
 */
public class ProjetoComponent extends javax.swing.JFrame {
    Caretaker c;
    int jb1h,jb1w;
    /**
     * Creates new form ProjetoComponent
     */
    public ProjetoComponent() {
        initComponents();
        //salvando o tamanho original
        jb1h = jButton1.getHeight();
        jb1w = jButton1.getWidth();
        c = new Caretaker();
        jButton1.addActionListener(c);
        jButton2.addActionListener(c);
        jButton3.addActionListener(c);
        jButton4.addActionListener(c);
        jButton5.addActionListener(c);
        jButton6.addActionListener(c);
        jButton1.addComponentListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Botão");
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 120, 70, 30);

        jButton2.setText("Esconder");
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 210, 110, 23);

        jButton3.setText("Mostrar");
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 240, 110, 23);

        jButton4.setText("Aumentar");
        getContentPane().add(jButton4);
        jButton4.setBounds(150, 210, 110, 23);

        jButton5.setText("Diminuir");
        getContentPane().add(jButton5);
        jButton5.setBounds(150, 240, 110, 23);

        jButton6.setText("Movimentar");
        getContentPane().add(jButton6);
        jButton6.setBounds(280, 210, 110, 50);

        jLabel1.setText("Status do Botão: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 100, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 10, 260, 40);

        setBounds(0, 0, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoComponent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    class Caretaker implements ActionListener,ComponentListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource() == jButton1){
                jTextField1.setText(e.getSource().getClass().getName() + " pressionado.");
            }else 
                if(e.getSource() == jButton2){
                    jButton1.setVisible(false);
                }else
                    if(e.getSource() == jButton3){
                        jButton1.setVisible(true);
                    }else
                        if(e.getSource() == jButton4){
                            if(jButton1.getHeight() < jButton6.getHeight()){
                                jButton1.setSize(jButton1.getWidth(), jButton1.getHeight()+1);
                            }
                            if(jButton1.getWidth() < jButton6.getWidth()){
                                jButton1.setSize(jButton1.getWidth()+1, jButton1.getHeight());
                            }
                        }else
                            if(e.getSource() == jButton5){
                                if(jButton1.getHeight() > jb1h){
                                    jButton1.setSize(jButton1.getWidth(), jButton1.getHeight()-1);
                                }
                                if(jButton1.getWidth() > jb1w){
                                    jButton1.setSize(jButton1.getWidth()-1, jButton1.getHeight());
                                }
                            }else
                                if(e.getSource() == jButton6){
                                    if(new Random().nextInt(10) > 4){
                                        if(jButton1.getX() > jButton2.getX()){
                                            jButton1.setLocation(jButton1.getX()-new Random().nextInt(10), jButton1.getY());
                                        }
                                    }else{
                                        if(jButton1.getX() < jButton6.getX()+jButton6.getWidth()){
                                            jButton1.setLocation(jButton1.getX()+new Random().nextInt(10), jButton1.getY());
                                        }
                                    }
                                }
            
        }

        @Override
        public void componentResized(ComponentEvent e) {
            if(e.getComponent() == jButton1){
                jTextField1.setText(e.getComponent().getClass().getName() + " foi redimensionado.");
            }
        }
        @Override
        public void componentMoved(ComponentEvent e) {
            if(e.getComponent() == jButton1){
                jTextField1.setText(e.getComponent().getClass().getName() + " se movimentou.");
            }
        }
        @Override
        public void componentShown(ComponentEvent e) {
            if(e.getComponent() == jButton1){
                jTextField1.setText(e.getComponent().getClass().getName() + " apareceu.");
            }
        }
        @Override
        public void componentHidden(ComponentEvent e) {
            if(e.getComponent() == jButton1){
                jTextField1.setText(e.getComponent().getClass().getName() + " foi escondido");
            }
        }
        
    
    }

}
