/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problema.pkg1;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author m78159
 */
public class JpanelString extends javax.swing.JPanel {
    public ArrayList<Integer> fai;
    private int fxNum;
    private String gType;
    Main m;
    Cts c;
    
    /**
     * Creates new form JpanelString
     */
    public JpanelString(Main m) {
        this.m = m;
        c = new Cts();
        gType = ""; fxNum = 1;
        fai = new ArrayList<>();
        this.setSize(400,300);
        initComponents();
        jButton1.addActionListener(c);
    }
    public String getGType(){
        return gType;
    }
    public int getfxNum(){
        return fxNum;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setText("Comando:");
        add(jLabel1);
        jLabel1.setBounds(37, 49, 65, 14);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(100, 40, 260, 30);

        jLabel2.setText("Insira no formato: plotar idade X (Faixa) tipo (Gráfico)");
        add(jLabel2);
        jLabel2.setBounds(30, 120, 340, 30);

        jLabel3.setText("Faixa: faixa1, faixa5, faixa10.");
        add(jLabel3);
        jLabel3.setBounds(30, 150, 210, 20);

        jLabel4.setText("Gráfico: barra, torta.");
        add(jLabel4);
        jLabel4.setBounds(30, 170, 220, 20);

        jButton1.setText("Criar Gráfico");
        add(jButton1);
        jButton1.setBounds(140, 200, 110, 23);

        jLabel5.setText("Status:");
        add(jLabel5);
        jLabel5.setBounds(40, 80, 60, 30);
        add(jTextField2);
        jTextField2.setBounds(100, 80, 260, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField2.setText("Agurandando comando...");
    }//GEN-LAST:event_jTextField1FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    class Cts implements ActionListener{
        private int max = 0;
        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource() == jButton1){
                String str = "";
                //lowers the sentence
                try{
                    if(m.pl.p.isEmpty())
                        throw new Exception(str = "Erro - Vetor não inicializado");
                    jTextField1.setText(jTextField1.getText().toLowerCase());
                    if(jTextField1.getText().contains("faixa10")){
                        fxNum = 10;
                    }else   if(jTextField1.getText().contains("faixa5")){
                                fxNum = 5;
                            }else   if(jTextField1.getText().contains("faixa1")){
                                        fxNum = 1;
                                    }else{
                                        throw new Exception(str = "Erro - faixa não estabelecida.");
                                    }
                    if(jTextField1.getText().contains("tipo torta")){
                        gType = "torta";
                        }else if(jTextField1.getText().contains("tipo barra")){
                                 gType = "barra";
                              }else{
                                  throw new Exception(str = "Erro - Tipo não especificado.");
                              }
                    //cria os espaços para salvar os valores do gráfico
                    max = setMax();
                    for(int x = 0; x < max/fxNum; x++){
                        fai.add(0);
                    }
                    setNewArray();
                    jTextField2.setText("Gráfico Criado!");
                }catch(Exception exc){
                    jTextField2.setText(str);
                }
            }
        }
        
        private int setMax(){
            for(Pessoa pe : m.pl.p){
                if(pe.getIdade()>max)
                    max = pe.getIdade();
            }
            while(max%fxNum != 0){
                max++;
            }
            return max;
        }
        
        private void setNewArray(){
            for(Pessoa pe : m.pl.p){
                int pos = 1;
                //topo parcial, para adicionar cada uma das idades em um grupo específico
                while(pos*fxNum <= max){
                    if(pe.getIdade() <= pos*fxNum){
                        fai.set((pos-1),(fai.get(pos-1)+1));
                        pos = max;
                    }
                    pos++;
                }
                    
            }
        }
    }

}
