/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problema.pkg1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author m78159
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Jpanel1 p1;
    Jpanel2 p2;
    JpanelLeit pl;
    JpanelString ps;
    Caretaker c;
    
    public Main() {
        initComponents();
        
        pl = new JpanelLeit(this);
        ps = new JpanelString(this);
        p1 = new Jpanel1(this);
        p2 = new Jpanel2(this);
        this.getContentPane().add(pl);
        pl.setBounds(0,0, pl.getWidth(), pl.getHeight());
        pl.setVisible(false);
        this.getContentPane().add(ps);
        ps.setBounds(0,0, ps.getWidth(), ps.getHeight());
        ps.setVisible(false);
        this.getContentPane().add(p1);
        p1.setBounds(0,0, p1.getWidth(), p1.getHeight());
        p1.setVisible(false);
        this.getContentPane().add(p2);
        p2.setBounds(0,0, p2.getWidth(), p2.getHeight());
        p2.setVisible(false);
        
        c = new Caretaker(this);
        jButton1.addActionListener(c);
        jButton2.addActionListener(c);
        jButton3.addActionListener(c);
        jButton4.addActionListener(c);
        jButton5.addActionListener(c);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Inserção");
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 260, 100, 23);

        jButton2.setText("Construção");
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 260, 100, 23);

        jButton3.setText("Exibição");
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 260, 120, 23);

        jButton4.setText("Tipo Torta");
        getContentPane().add(jButton4);
        jButton4.setBounds(70, 290, 120, 23);

        jButton5.setText("Tipo Barra");
        getContentPane().add(jButton5);
        jButton5.setBounds(210, 290, 120, 23);

        setBounds(0, 0, 416, 363);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables

    class Caretaker implements ActionListener{
        Main m;
        Caretaker(Main m){
            this. m = m;
        }
        
        
        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource() == jButton1){
                m.pl.setVisible(true);
                m.p1.setVisible(false);
                m.p2.setVisible(false);
                m.ps.setVisible(false);
                jButton2.setVisible(true);
                jButton4.setVisible(false);
                jButton5.setVisible(false);
            }else
                if(e.getSource() == jButton2){
                    m.ps.fai.clear();
                    m.ps.setVisible(true);
                    m.pl.setVisible(false);
                    m.p1.setVisible(false);
                    m.p2.setVisible(false);
                    jButton3.setVisible(true);
                    jButton4.setVisible(false);
                    jButton5.setVisible(false);
                }else
                    if(e.getSource() == jButton3){
                        m.ps.setVisible(false);
                        m.pl.setVisible(false);
                        if(m.ps.getGType().equals("torta")){
                            m.p1.makeChart();
                            m.p1.setVisible(true);
                            m.p2.setVisible(false);
                            jButton5.setVisible(true);
                        }else{
                            m.p2.makeChart();
                            m.p1.setVisible(false);
                            m.p2.setVisible(true);
                            jButton4.setVisible(true);
                        }
                        }else 
                            if(e.getSource() == jButton4){
                                m.p1.makeChart();
                                m.p2.setVisible(false);
                                m.p1.setVisible(true);
                                jButton4.setVisible(false);
                                jButton5.setVisible(true);
                            }else
                                if(e.getSource() == jButton5){
                                m.p2.makeChart();
                                m.p1.setVisible(false);
                                m.p2.setVisible(true);
                                jButton5.setVisible(false);
                                jButton4.setVisible(true);
                                }
                        
        }
    }
}
